#!/usr/bin/env python

import os
import sys
import time
import argparse
from fabric.api import env
from handsfree import FabricSupport

parser = argparse.ArgumentParser()
parser.add_argument('--host', '-H', help='VM Hostname')
parser.add_argument('--user', '-u', help='VM Shell User (Default: root)')
parser.add_argument(
    '--key', '-k', help='VM Shell User Key (Default: ~/.ssh/id_rsa)')
parser.add_argument('--version', '-v', help='DCM Version')
cmd_args = parser.parse_args()

if cmd_args.host is not None and cmd_args.version is not None:
    env.skip_bad_hosts = True

    if cmd_args.user is None:
        env.user = 'root'
    else:
        env.user = cmd_args.user

    if cmd_args.key is None:
        env.key_filename = os.path.expanduser('~') + '/.ssh/id_rsa'
    else:
        env.key_filename = cmd_args.key

    total_start = time.time()
    fab = FabricSupport(
        cmd_args.version, "/tmp/es-onpremise-chef-solo-" + cmd_args.version)
    print "Starting install of DCM version " + cmd_args.version
    fab.execute("fetch_vm_info", cmd_args.host)
    fab.execute("deps", cmd_args.host)
    fab.execute("fetch_release", cmd_args.host)
    fab.execute("run_setup", cmd_args.host)
    fab.execute("install_release", cmd_args.host)
    print '*** Script finished in', round(time.time() - total_start, 3), 'seconds.'
else:
    parser.print_help()
    sys.exit(1)
