#!/usr/bin/env python

import sys
import argparse
from handsfree import FabricSupport

parser = argparse.ArgumentParser()
parser.add_argument('--host', '-H', help='VM Hostname')
cmd_args = parser.parse_args()

if cmd_args.host is not None:
    fab = FabricSupport()
    fab.execute("df", cmd_args.host)
else:
    parser.print_help()
    sys.exit(1)
