sudo: false
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - "if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi"
install: "pip install -r requirements.txt --use-mirrors"
script: nosetests
